apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  devEnvironments:
    defaultEditor: che-incubator/che-code/latest
    defaultNamespace:
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: -1
    secondsOfRunBeforeIdling: -1
    maxNumberOfRunningWorkspacesPerUser: 2
    storage:
      pvcStrategy: per-user
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard: {}
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
